<script lang="ts">
	import * as icons from 'lucide-svelte/icons/index';

	interface IconProps {
		name: string;
		size?: number;
		strokeWidth?: number;
		class?: string;
	}

	let { name, size = 20, strokeWidth = 2, class: className = '' }: IconProps = $props();

	const iconNames: Record<string, string> = {
		'dashboard': 'LayoutDashboard',
		'home': 'Home',
		'search': 'Search',
		'menu': 'Menu',
		'grid': 'LayoutGrid',
		'list': 'List',
		'filter': 'Filter',
		'book': 'Book',
		'book-open': 'BookOpen',
		'graduation': 'GraduationCap',
		'trophy': 'Trophy',
		'crown': 'Crown',
		'award': 'Award',
		'shield-check': 'ShieldCheck',
		'wallet': 'Wallet',
		'credit-card': 'CreditCard',
		'dollar': 'DollarSign',
		'gift': 'Gift',
		'coupon': 'Ticket',
		'file': 'File',
		'file-text': 'FileText',
		'folder': 'Folder',
		'image': 'Image',
		'download': 'Download',
		'upload': 'Upload',
		'archive': 'Archive',
		'edit': 'PenLine',
		'delete': 'Trash2',
		'copy': 'Copy',
		'save': 'Save',
		'share': 'Share2',
		'link': 'Link',
		'external': 'ExternalLink',
		'print': 'Printer',
		'check': 'Check',
		'x': 'X',
		'plus': 'Plus',
		'arrow-right': 'ArrowRight',
		'arrow-left': 'ArrowLeft',
		'chevron-right': 'ChevronRight',
		'chevron-down': 'ChevronDown',
		'chevron-up': 'ChevronUp',
		'bell': 'Bell',
		'sun': 'Sun',
		'moon': 'Moon',
		'settings': 'Settings',
		'help': 'HelpCircle',
		'logout': 'LogOut',
		'play': 'Play',
		'pause': 'Pause',
		'skip-back': 'SkipBack',
		'skip-forward': 'SkipForward',
		'repeat': 'Repeat',
		'shuffle': 'Shuffle',
		'volume': 'Volume2',
		'volume-mute': 'VolumeX',
		'mic': 'Mic',
		'mic-off': 'MicOff',
		'video': 'Video',
		'film': 'Film',
		'music': 'Music',
		'disc': 'Disc',
		'broadcast': 'Radio',
		'globe': 'Globe',
		'wifi': 'Wifi',
		'wifi-off': 'WifiOff',
		'signal': 'Signal',
		'hard-drive': 'HardDrive',
		'server': 'Server',
		'database': 'Database',
		'cloud': 'Cloud',
		'cloud-off': 'CloudOff',
		'laptop': 'Laptop',
		'smartphone': 'Smartphone',
		'tablet': 'Tablet',
		'keyboard': 'Keyboard',
		'lock': 'Lock',
		'unlock': 'Unlock',
		'eye': 'Eye',
		'loading': 'RefreshCw',
		'chart': 'BarChart3',
		'bar-chart-2': 'BarChart2',
		'trending': 'TrendingUp',
		'activity': 'Activity',
		'zap': 'Zap',
		'layers': 'Layers',
		'check-circle': 'CheckCircle2',
		'building': 'Building2',
		'store': 'Building2',
		'calendar': 'Calendar',
		'clock': 'Clock',
		'star': 'Star',
		'flag': 'Flag',
		'map-pin': 'MapPin',
		'map': 'Map',
		'compass': 'Compass',
		'target': 'Target',
		'package': 'Package',
		'box': 'Box',
		'boxes': 'Boxes',
		'sparkle': 'Sparkles',
		'rocket': 'Rocket',
		'lightbulb': 'Lightbulb',
		'puzzle': 'Puzzle',
		'users': 'Users',
		'user': 'User',
		'heart': 'Heart',
		'thumbs-up': 'ThumbsUp',
		'thumbs-down': 'ThumbsDown',
		'message': 'MessageSquare',
		'message-circle': 'MessageCircle',
		'mail': 'Mail',
		'phone': 'Phone',
		'anchor': 'Anchor',
		'plane': 'Plane',
		'train': 'Train',
		'car': 'Car',
		'truck': 'Truck',
		'bike': 'Bike',
		'footprints': 'Footprints',
		'utensils': 'UtensilsCrossed',
		'coffee': 'Coffee',
		'beer': 'Beer',
		'wine': 'Wine',
		'pizza': 'Pizza',
		'tea': 'Tea',
		'cookie': 'Cookie',
		'apple': 'Apple',
		'mountain': 'Mountain',
		'party-popper': 'PartyPopper',
		'flame': 'Flame',
		'shield': 'Shield',
		'pen-tool': 'PenTool',
		'megaphone': 'Megaphone',
		'hammer': 'Hammer',
		'refresh-ccw': 'RefreshCcw'
	};

	const pascalName = $derived(iconNames[name] || iconNames['help'] || 'HelpCircle');
	const IconComponent = $derived((icons as any)[pascalName]);
</script>

{#if IconComponent}
	<IconComponent {size} {strokeWidth} class={className} />
{:else}
	<span class={className} style="width: {size}px; height: {size}px; display: inline-flex;">?</span>
{/if}
